### ISSUE TITLE
when scrolling to the bottom of the channel list, the visual scroll spasms and you can't left or right click anything in the channel list anymore until you scroll back uop

### ISSUE THREAD

**Issue by jack652** [Saltssaumure/pios-discord-theme#10] opened 2022-04-02 18:59 UTC
when scrolling to the bottom of the channel list, the visual scroll slider spasms and you can't left or right click anything in the channel list anymore until you scroll back up

https://user-images.githubusercontent.com/48365199/161397458-5c814644-0bd6-4c96-8f7a-0779fdab5647.mp4

**Comment by Saltssaumure** [comment] 2022-04-09 04:51
First thing first, thanks for the bug report and also nice music in the recording!

The issue is now fixed, but the appearance of the channel and user lists also had to change.

The scrolling bug was caused by some part of Discord's JS loading and unloading channels as you scroll, which breaks down when the height of elements in the channel list are not the default height. [Video demo](https://www.youtube.com/watch?v=EEiK4sl8ZtQ)

This issue was also seen in the [Lavender theme](https://github.com/Lavender-Discord/Lavender/releases/tag/v2.0.0), and resolved by using a plugin to smooth the scroll. However, this only works for shorter channel lists and eventually fails for very long channel lists.

So until someone with more JS skills than me can fix the problem on the JS side, all I can do to resolve the issue is to return all elements to the original size and fit the dashed line in between the default position of the groups.

**Closed by Saltssaumure** 2022-04-09 04:51 UTC
